version: '3.7'
services:
  fast-data-dev:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: localhost
    ports:
      - "2181:2181"   # Zookeeper
      - "3030:3030"   # Kafka Topics UI
      - "8081-8083:8081-8083"  # Schema Registry, REST Proxy, Connect UI
      - "9581-9585:9581-9585"  # JMX Ports
      - "9092:9092"   # Kafka Broker
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge